/**
 * Stage 9 — publishing metadata. Version 1.
 *
 * Versioned like every other prompt here. The reason is sharper for this one than for most:
 * a title and description are what a platform's policy team reads if a video is ever
 * appealed, and "generated by claude-opus-5" without the instructions is not evidence of
 * anything.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * The uniqueness requirement is not a style note
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * ARCHITECTURE.md §0.2: YouTube's inauthentic-content policy names templated output with
 * minor substitutions as the disqualifying pattern, and metadata is where that pattern is
 * most visible — a channel whose last twelve titles are "Why X is actually Y" is legible as
 * templated from the titles alone, whatever the videos contain.
 *
 * So the recent titles are in the prompt, and the instruction is not "be original" but
 * "do not reuse the *shape*". Those are different asks. A model told to be original will
 * change the nouns; a model told the shapes already used will change the construction.
 *
 * ── Disclosure is asked for, not inferred ────────────────────────────────────
 *
 * `publications.altered_content_disclosed` is a compliance field. Every video this pipeline
 * makes is synthetic, so the answer is always true — which is exactly why the model is not
 * asked to decide it. A field whose value is a policy fact must not be a model's opinion.
 * It is set by the code and mentioned here so nobody adds it to the schema later.
 */

export const PROMPT_ID = '09-metadata';
export const PROMPT_VERSION = 1;
export const PROMPT_REF = `${PROMPT_ID}.v${PROMPT_VERSION}`;

export interface MetadataPromptInput {
  readonly channel: { name: string; platform: string; niche: string };
  readonly concept: { title: string; angle: string };
  /** The script's hook and voiceover — what the video actually says. */
  readonly hook: string;
  readonly voText: string;
  /** Titles already published or queued on this channel. The anti-template input. */
  readonly recentTitles: readonly string[];
  readonly durationSeconds: number;
}

export const SYSTEM_PROMPT = `You write the publishing metadata for one short-form video.

You are given the concept, the angle, the hook and the full voiceover. Write metadata that
describes THIS video. Do not restate the concept title — a viewer sees the title, not the
concept.

TITLE
  Under 70 characters so it does not truncate in a feed.
  It must be a claim or a question a specific person would click, not a category label.
  "Road salt is dissolving your bridges" beats "The problem with road salt".

DESCRIPTION
  Two to four sentences. The first sentence has to work alone — most surfaces show only it.
  Say what the video argues, not what it "explores" or "dives into".
  No calls to subscribe, no emoji, no hashtag block.

TAGS
  Five to twelve. Lowercase. Specific over broad: "urban heat island" over "science".
  No tag that is just a restatement of the title.

DO NOT REUSE THE SHAPE OF A RECENT TITLE.
You will be shown titles already on this channel. The requirement is structural, not
lexical: if three recent titles are "Why X is actually Y", do not write a fourth with
different nouns. Change the construction — a question, a flat claim, a number, a
contradiction. Reusing a shape is the pattern platforms treat as templated output, and it is
visible from the titles alone regardless of what the videos contain.

Return ONLY valid JSON matching the schema. No prose, no code fences.`;

export function buildUserMessage(input: MetadataPromptInput): string {
  const { channel, concept, hook, voText, recentTitles, durationSeconds } = input;

  const recentBlock = recentTitles.length
    ? recentTitles.map((t) => `- ${t}`).join('\n')
    : '(nothing published on this channel yet — you are setting the pattern, so pick a ' +
      'construction you would be happy to see varied rather than repeated)';

  return `CHANNEL
  name: ${channel.name}
  platform: ${channel.platform}
  niche: ${channel.niche}

CONCEPT
  title: ${concept.title}
  angle: ${concept.angle}

THE VIDEO
  runtime: ${Math.round(durationSeconds)}s
  hook: ${hook}
  voiceover:
${voText
  .split('\n')
  .map((l) => `    ${l}`)
  .join('\n')}

RECENT TITLES ON THIS CHANNEL — do not reuse these shapes
${recentBlock}`;
}
