#!/usr/bin/env node
/**
 * pnpm bible:import — copy a channel's bible folder (channels/<slug>/) into the database
 * tables `channel_bibles` + `channel_characters` (migration 0048, decision 0022).
 *
 * Two transports, ONE row builder (`bibleRows` in src/lib/bureau/bible.ts), so the local
 * import and the hosted paste cannot say different things:
 *
 *   --db <url>     import into a database you can reach (local scratch cluster, a harness).
 *                  Runs `importFolderBible`: insert-if-absent, then fold Voices-screen
 *                  overrides into the cast. Idempotent — a second run changes nothing, and it
 *                  never overwrites an edit made in the app.
 *   --sql <out>    write the same rows as SQL for the Supabase SQL editor (the hosted project
 *                  is reachable only by pasting — 0008). `on conflict do nothing` throughout;
 *                  a guard at the end raises if the channel got no bible (wrong slug), which
 *                  rolls the whole paste back. `db-bundle.mjs --append` puts it inside the
 *                  migration bundle's transaction.
 *
 *   node scripts/bible-import.mjs [--channel bureau-of-reality] (--db <url> | --sql <out>)
 */
import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const so = require.resolve('server-only');
require.cache[so] = { id: so, filename: so, loaded: true, exports: {}, paths: [], children: [] };
const B = new URL('../.verify-build/src/lib', import.meta.url).pathname;
const { bibleForSlug, bibleRows } = require(`${B}/bureau/bible.js`);
const { TTS_PRESET_IDS } = require(`${B}/drivers/voice-route.js`);

const argv = process.argv.slice(2);
const arg = (n) => (argv.includes(`--${n}`) ? argv[argv.indexOf(`--${n}`) + 1] : undefined);
const slug = arg('channel') ?? 'bureau-of-reality';
const dbUrl = arg('db');
const sqlOut = arg('sql');
if (!dbUrl === !sqlOut) {
  console.error('usage: node scripts/bible-import.mjs [--channel <slug>] (--db <url> | --sql <out.sql>)');
  process.exit(2);
}
const cb = bibleForSlug(slug);

if (dbUrl) {
  const pg = (await import('pg')).default;
  const client = new pg.Client({ connectionString: dbUrl });
  await client.connect();
  const { supabaseShim } = await import('./lib/supabase-shim.mjs');
  const { importFolderBible } = require(`${B}/channels/bible-admin.js`);
  const { getBible } = require(`${B}/bureau/bible.js`);
  const { bibleDiff } = require(`${B}/channels/bible-admin.js`);
  const db = supabaseShim(client);
  const [ch] = (await client.query('select id from channels where slug = $1', [slug])).rows;
  if (!ch) {
    console.error(`No channel with slug ${slug}.`);
    process.exit(2);
  }
  const r = await importFolderBible(db, { channelId: ch.id, slug, by: `import:channels/${slug}` });
  const fromDb = await getBible(db, ch.id);
  const diff = bibleDiff(cb, fromDb);
  console.log(`${slug}: bible ${r.bible}, ${r.characters} character(s) inserted, overrides folded: ${r.foldedOverrides.join(', ') || 'none'}; read back from ${fromDb.source}; ${diff.length ? `${diff.length} field(s) differ from the folder (edits made in the app, or folded voices)` : 'identical to the folder field by field'}.`);
  await client.end();
  process.exit(fromDb.source === 'db' ? 0 : 1);
}

// ── SQL for the paste bundle ─────────────────────────────────────────────────
const lit = (v) => (v === null || v === undefined ? 'null' : typeof v === 'number' || typeof v === 'boolean' ? String(v) : `'${String(v).replace(/'/g, "''")}'`);
const json = (v) => `${lit(JSON.stringify(v ?? null))}::jsonb`;
const CH = `(select id from channels where slug = ${lit(slug)})`;
const rows = bibleRows(cb, '00000000-0000-0000-0000-000000000000', `import:channels/${slug}`);
const b = rows.bible;
const charCols = ['slug', 'name', 'role', 'desk', 'on_screen', 'season_introduced', 'personality', 'accent_hex', 'voice', 'voice_brief', 'visual_lock', 'catchphrase', 'speech_rules', 'never_do', 'reference_frame', 'sort', 'active'];
const jsonCols = new Set(['voice', 'visual_lock', 'catchphrase', 'speech_rules', 'never_do', 'reference_frame']);
const presets = TTS_PRESET_IDS.map(lit).join(', ');

const sql = `-- ════════════════════════════════════════════════════════════════════════════
-- Import: channels/${slug}/ → channel_bibles + channel_characters (0022)
-- GENERATED by scripts/bible-import.mjs from the JSON in the repo. Do not edit by hand.
-- Idempotent: on conflict do nothing — an edit already made in the app is never overwritten.
-- ════════════════════════════════════════════════════════════════════════════

insert into channel_bibles (channel_id, world, publishing, series, policy, trend_sources, version, updated_by)
select ${CH}, ${json(b.world)}, ${json(b.publishing)}, ${json(b.series)}, ${json(b.policy)}, ${json(b.trend_sources)}, ${b.version}, ${lit(b.updated_by)}
 where ${CH} is not null
on conflict (channel_id) do nothing;

insert into channel_characters (channel_id, ${charCols.join(', ')})
select ${CH}, v.* from (values
${rows.characters.map((c) => `  (${charCols.map((k) => (jsonCols.has(k) ? json(c[k]) : lit(c[k]))).join(', ')})`).join(',\n')}
) as v(${charCols.join(', ')})
 where ${CH} is not null
on conflict (channel_id, slug) do nothing;

-- Voices chosen on the Voices screen (0046) become the cast's own voice; the override rows go.
-- Only an override the router would accept is folded (a known preset, or a direct voice id).
update channel_characters cc
   set voice = case when o.voice_provider = 'runway'
                    then jsonb_build_object('provider', 'runway', 'preset_id', o.voice_id, 'direct_voice_id', cc.voice->'direct_voice_id')
                    else jsonb_build_object('provider', o.voice_provider, 'preset_id', cc.voice->'preset_id', 'direct_voice_id', o.voice_id) end,
       updated_at = now()
  from channel_voice_overrides o
 where o.channel_id = ${CH} and cc.channel_id = o.channel_id and cc.slug = o.character_slug
   and ((o.voice_provider = 'runway' and o.voice_id in (${presets})) or (o.voice_provider = 'elevenlabs' and length(trim(o.voice_id)) > 0));

delete from channel_voice_overrides o
 where o.channel_id = ${CH}
   and ((o.voice_provider = 'runway' and o.voice_id in (${presets})) or (o.voice_provider = 'elevenlabs' and length(trim(o.voice_id)) > 0))
   and exists (select 1 from channel_characters cc where cc.channel_id = o.channel_id and cc.slug = o.character_slug);

do $kiln_import$
begin
  if ${CH} is null then
    raise exception 'No channel with slug ${slug}: the bible import has nothing to attach to. Nothing in this file has been applied.';
  end if;
  if (select count(*) from channel_characters where channel_id = ${CH}) < ${rows.characters.length} then
    raise exception 'The ${slug} cast did not import completely. Nothing in this file has been applied.';
  end if;
end
$kiln_import$;
`;
writeFileSync(sqlOut, sql);
console.log(`wrote ${sqlOut}: the ${slug} bible, ${rows.characters.length} character(s), ${Object.keys(b.series).length} series.`);
