#!/usr/bin/env node
/**
 * data/kiln-topic-calendar.csv → the INSERTs in supabase/migrations/0038_calendar_seed.sql.
 *
 *   node scripts/calendar-sql.mjs            print the SQL
 *   node scripts/calendar-sql.mjs --write    rewrite the migration body
 *   node scripts/calendar-sql.mjs --check    exit 1 if the migration and the CSV disagree
 *
 * The CSV is the plan's source of truth; the migration is how it reaches a database. Two
 * copies of one fact drift, so `--check` runs in `pnpm check` (as `check:calendar`) and
 * fails the moment someone edits one without regenerating the other. A migration is
 * forward-only, so a calendar change after 0038 has been applied anywhere belongs in a NEW
 * migration — `--check` then compares against the union of seed files (see SEED_FILES).
 */

import { readFileSync, writeFileSync } from 'node:fs';

const CSV = 'data/kiln-topic-calendar.csv';
const MIGRATION = 'supabase/migrations/0038_calendar_seed.sql';
const CHANNEL = 'b0000000-0000-4000-8000-000000000001';

export function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = '';
  let quoted = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (quoted) {
      if (c === '"' && text[i + 1] === '"') {
        field += '"';
        i++;
      } else if (c === '"') quoted = false;
      else field += c;
    } else if (c === '"') quoted = true;
    else if (c === ',') {
      row.push(field);
      field = '';
    } else if (c === '\n' || c === '\r') {
      if (c === '\r' && text[i + 1] === '\n') i++;
      row.push(field);
      field = '';
      if (row.some((f) => f !== '')) rows.push(row);
      row = [];
    } else field += c;
  }
  if (field !== '' || row.length) {
    row.push(field);
    if (row.some((f) => f !== '')) rows.push(row);
  }
  return rows;
}

const q = (v) => (v === '' || v === undefined ? 'null' : `'${String(v).replace(/'/g, "''")}'`);

export function calendarRows() {
  const [header, ...body] = parseCsv(readFileSync(CSV, 'utf8'));
  const expect = 'slot,date,weekday,format,series,series_name,lead,episode,topic,hook,seasonal_tag,status,notes';
  if (header.join(',') !== expect) {
    throw new Error(`Calendar header changed:\n  got      ${header.join(',')}\n  expected ${expect}`);
  }
  return body.map((r) => Object.fromEntries(header.map((h, i) => [h, r[i] ?? ''])));
}

export function calendarSql() {
  const rows = calendarRows();
  const values = rows.map((r) => {
    const kind = r.slot.startsWith('B') ? 'bank' : r.format === 'long_form' ? 'long_form' : 'short';
    return `  (${[
      q(r.slot), `'${CHANNEL}'`, q(kind), r.date ? `'${r.date}'` : 'null', q(r.series),
      q(r.series_name), q(r.lead), q(r.episode), q(r.topic), q(r.hook), q(r.seasonal_tag),
      q(r.status), q(r.notes),
    ].join(', ')})`;
  });
  return (
    `insert into slots (id, channel_id, kind, slot_date, series, series_name, lead, episode, topic, hook, seasonal_tag, topic_status, notes) values\n` +
    values.join(',\n') +
    `\non conflict (id) do nothing;\n`
  );
}

const HEADER = `-- 0038 — the topic calendar, seeded from data/kiln-topic-calendar.csv.
--
-- GENERATED by scripts/calendar-sql.mjs --write. Do not edit by hand; \`pnpm check:calendar\`
-- fails if this file and the CSV disagree. 164 dated Shorts (S###), 12 long-form (L##),
-- 16 bank slots (B##).

`;

const mode = process.argv[2];
if (mode === '--write') {
  writeFileSync(MIGRATION, HEADER + calendarSql());
  console.log(`wrote ${MIGRATION} (${calendarRows().length} slots)`);
} else if (mode === '--check') {
  let current = '';
  try {
    current = readFileSync(MIGRATION, 'utf8');
  } catch {
    console.error(`FAIL  ${MIGRATION} does not exist — run node scripts/calendar-sql.mjs --write`);
    process.exit(1);
  }
  if (current !== HEADER + calendarSql()) {
    console.error(`FAIL  ${MIGRATION} disagrees with ${CSV}. Regenerate it (or, if 0038 is already applied somewhere, add a new migration).`);
    process.exit(1);
  }
  console.log(`PASS  calendar migration matches the CSV (${calendarRows().length} slots)`);
} else {
  process.stdout.write(calendarSql());
}
